"""Stub file for custom_components/reflex_map3d/_base.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex.components.component import NoSSRComponent

__all__ = ["FRONTEND_FILES", "NPM_DEPENDENCIES", "Map3dComponent", "asset_library"]
NPM_DEPENDENCIES: list[str]
FRONTEND_FILES: tuple[str, ...]
_ASSETS: dict[str, str]

def asset_library(filename: str) -> str: ...

class Map3dComponent(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Map3dComponent":
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...
