"""Stub file for custom_components/reflex_map3d/area_selector.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ._base import Map3dComponent

__all__ = ["Map3dAreaSelector", "map3d_area_selector"]
DEFAULT_TILE_URL = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
DEFAULT_ATTRIBUTION = (
    '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
)

class Map3dAreaSelector(Map3dComponent):
    @classmethod
    def create(
        cls,
        *children,
        center: Var[list[float]] | list[float] | None = None,
        zoom: Var[int] | int | None = None,
        tile_url: Var[str] | str | None = None,
        attribution: Var[str] | str | None = None,
        min_zoom: Var[int] | int | None = None,
        max_zoom: Var[int] | int | None = None,
        rectangle_color: Var[str] | str | None = None,
        show_controls: Var[bool] | bool | None = None,
        select_label: Var[str] | str | None = None,
        drag_label: Var[str] | str | None = None,
        clear_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_clear: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mode_change: Optional[EventType[Any]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_select: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Map3dAreaSelector":
        """Create the selector, defaulting to a usable size.

        Leaflet needs a sized container, so a default height is applied unless
        the caller sets one.

        Args:
            *children: Extra nodes rendered on top of the map.
            center: Where the map opens, as ``[lat, lng]``.
            zoom: The initial zoom level.
            tile_url: The XYZ raster tile template to render.
            attribution: The attribution shown in the map corner. Keep it when using OSM tiles.
            min_zoom: The smallest zoom level the user may reach.
            max_zoom: The largest zoom level the user may reach.
            rectangle_color: The stroke colour of the selection rectangle.
            show_controls: Whether to render the built-in mode/clear buttons.
            select_label: Label of the button that switches into rectangle-drawing mode.
            drag_label: Label of the button that switches back to panning.
            clear_label: Label of the button that clears the current selection.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_select: Fired with the bounding box whenever the user finishes a drag.
            on_clear: Fired when the user clears the current selection.
            on_mode_change: Fired with ``True`` for pan mode and ``False`` for draw mode.
            **props: The component props.

        Returns:
            The component instance.
        """
        ...

map3d_area_selector = Map3dAreaSelector.create
