"""Stub file for custom_components/reflex_map3d/viewer.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from ._base import Map3dComponent

__all__ = ["Map3dViewer", "map3d_viewer"]

class Map3dViewer(Map3dComponent):
    @classmethod
    def create(
        cls,
        *children,
        center: Var[list[float]] | list[float] | None = None,
        zoom: Var[int] | int | None = None,
        tile_url: Var[str] | str | None = None,
        attribution: Var[str] | str | None = None,
        overpass_url: Var[str] | str | None = None,
        overpass_timeout: Var[int] | int | None = None,
        include_roads: Var[bool] | bool | None = None,
        max_span: Var[float] | float | None = None,
        scale: Var[int] | int | None = None,
        default_height: Var[float] | float | None = None,
        level_height: Var[float] | float | None = None,
        building_color: Var[str] | str | None = None,
        highlight_color: Var[str] | str | None = None,
        road_color: Var[str] | str | None = None,
        road_width: Var[float] | float | None = None,
        show_tooltip: Var[bool] | bool | None = None,
        show_sky: Var[bool] | bool | None = None,
        show_environment: Var[bool] | bool | None = None,
        environment_preset: Var[str] | str | None = None,
        drive_mode: Var[bool] | bool | None = None,
        export_filename: Var[str] | str | None = None,
        title: Var[str] | str | None = None,
        description: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_building_click: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_error: Optional[EventType[Any]] = None,
        on_export: Optional[EventType[Any]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_load: Optional[EventType[Any]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_select: Optional[EventType[Any]] = None,
        on_step_change: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Map3dViewer":
        """Create the viewer, defaulting to a usable size.

        Args:
            *children: Extra nodes rendered inside the viewer shell.
            center: Where the map opens, as ``[lat, lng]``.
            zoom: The initial zoom level.
            tile_url: The XYZ raster tile template to render.
            attribution: The attribution shown in the map corner.
            overpass_url: The Overpass endpoint the viewer downloads from.
            overpass_timeout: The Overpass server-side timeout in seconds.
            include_roads: Whether road centre lines are downloaded and rendered.
            max_span: Area size in degrees (dlat + dlng) above which the viewer warns first.
            scale: World units per degree of latitude.
            default_height: Height in metres for buildings with no height information.
            level_height: Metres per floor, used when a building only tags ``building:levels``.
            building_color: The colour of an idle building.
            highlight_color: The colour of a hovered or selected building.
            road_color: The colour of the road lines.
            road_width: The width of the road lines.
            show_tooltip: Whether hovering a building opens its OpenStreetMap tag panel.
            show_sky: Whether the drei sky dome is rendered.
            show_environment: Whether an image-based lighting environment is applied.
            environment_preset: The drei environment preset ("city", "sunset", "dawn", "night", ...).
            drive_mode: Whether to drive a car through the city with WASD instead of orbiting.
            export_filename: The file name of the exported GLB.
            title: The heading shown on the area-selection step.
            description: The paragraph shown on the area-selection step.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_select: Fired with the bounding box whenever the user finishes a drag.
            on_load: Fired with ``{"buildings", "roads", "bbox"}`` once the data is downloaded.
            on_export: Fired with ``{"filename", "bytes"}`` once a GLB export finishes.
            on_step_change: Fired with ``{"step", "name"}`` when the workflow advances.
            on_building_click: Fired with ``{"id", "tags", "selected"}`` when a building is clicked.
            on_error: Fired with an error message when a fetch or an export fails.
            **props: The component props.

        Returns:
            The component instance.
        """
        ...

map3d_viewer = Map3dViewer.create
